#!/usr/bin/env bash
#
# OmiSu — shared theme generator.
# A theme file (themes/<name>) holds bare 6-digit hex values; we render them
# into a Hyprland include and a Waybar CSS include for the active user.
#
# Expects OMISU_PATH / OMISU_USER / OMISU_HOME to be set by the caller.
#

omisu_theme_root() {
  printf '%s\n' "${OMISU_PATH:-${OmiSu_ROOT:-/usr/share/omisu}}"
}

# Generate an OmiSu-themed CSS for TriliumNext and drop it into its themes dir.
# TriliumNext picks it up under Settings -> Appearance -> Theme (best-effort;
# we can't force-select without editing its document DB).
omisu_theme_triliumnext() {
  local name="$1" ACCENT="$2" BG="$3" FG="$4" INACTIVE="$5"
  local omisu_home="${OMISU_HOME:-${OmiSu_HOME:-$HOME}}"
  local dirs=(
    "$omisu_home/.local/share/trilium-next/themes/OmiSu"
    "$omisu_home/.config/trilium-next/themes/OmiSu"
    "/etc/skel/.local/share/trilium-next/themes/OmiSu"
  )
  local css
  css="$(cat <<'CEOF'
/* OmiSu theme for TriliumNext — generated by omisu-theme, do not edit */
:root {
  --omisu-bg: @@BG@@;
  --omisu-fg: @@FG@@;
  --omisu-accent: @@ACCENT@@;
  --omisu-inactive: @@INACTIVE@@;
}
body, .app-container, .note-split, .note-detail, .note-editor, .note-title {
  background-color: @@BG@@ !important;
  color: @@FG@@ !important;
}
.note-title, a, .link, .attribute-title, .toc-entry {
  color: @@ACCENT@@ !important;
}
.window-header, .ribbon-container, .tab-row, .note-paths, .saved-status {
  background-color: @@BG@@ !important;
  border-color: @@INACTIVE@@ !important;
}
CEOF
)"
  css="${css//@@BG@@/#$BG}"; css="${css//@@FG@@/#$FG}"
  css="${css//@@ACCENT@@/#$ACCENT}"; css="${css//@@INACTIVE@@/#$INACTIVE}"
  for d in "${dirs[@]}"; do
    mkdir -p "$d" 2>/dev/null || continue
    printf '%s\n' "$css" > "$d/OmiSu.css" 2>/dev/null || true
  done
}

omisu_apply_theme() {
  local name="$1"
  local root
  root="$(omisu_theme_root)"
  local src="$root/themes/flat/$name"
  if [[ ! -f "$src" ]]; then
    src="$root/themes/$name"
  fi
  [[ -f "$src" ]] || { echo "OmiSu: unknown theme '$name'" >&2; return 1; }

  local omisu_home="${OMISU_HOME:-${OmiSu_HOME:-$HOME}}"
  local omisu_user="${OMISU_USER:-${OmiSu_USER:-$(id -un)}}"

  local ACCENT BG FG INACTIVE
  ACCENT=$(  awk -F= '/^ACCENT=/  {print $2}' "$src")
  BG=$(      awk -F= '/^BG=/      {print $2}' "$src")
  FG=$(      awk -F= '/^FG=/      {print $2}' "$src")
  INACTIVE=$(awk -F= '/^INACTIVE=/{print $2}' "$src")

  local share_dir="$omisu_home/.local/share/omisu"
  mkdir -p "$share_dir"

  # --- Hyprland theme --------------------------------------------------------
  cat > "$share_dir/hypr-theme.conf" <<EOF
# Generated by OmiSu — do not edit. Change with: omisu-theme <name>
col.active_border = 0x$ACCENT
col.inactive_border = 0x$INACTIVE
EOF

  # --- Waybar theme ----------------------------------------------------------
  cat > "$share_dir/waybar-theme.css" <<EOF
/* Generated by OmiSu — do not edit. Change with: omisu-theme <name> */
@define-color accent #$ACCENT;
@define-color bg #$BG;
@define-color fg #$FG;
@define-color inactive #$INACTIVE;
@define-color accent-dim alpha(#$ACCENT, 0.6);
@define-color red #f38ba8;
@define-color green #a6e3a1;
@define-color yellow #f9e2af;
@define-color blue #89b4fa;
@define-color magenta #f5c2e7;
@define-color cyan #94e2d5;
@define-color surface #313244;
@define-color surface1 #45475a;
@define-color surface2 #585b70;
EOF

  # --- Mako theme ------------------------------------------------------------
  cat > "$share_dir/mako-theme.conf" <<EOF
# Generated by OmiSu — do not edit. Change with: omisu-theme <name>
background-color=#$BG
text-color=#$FG
border-color=#$ACCENT

progress-color=#$ACCENT
progress-background=#$INACTIVE

border-radius=8
padding=12
margin=8
max-width=400

default-timeout=5000
ignored-timeout=0
layer=top

[urgency=low]
background-color=#$BG
border-color=#$INACTIVE
text-color=#$FG

[urgency=normal]
background-color=#$BG
border-color=#$ACCENT
text-color=#$FG

[urgency=critical]
background-color=#$BG
border-color=#f38ba8
text-color=#f38ba8
EOF

  # --- Wofi theme ------------------------------------------------------------
  cat > "$share_dir/wofi-theme.css" <<EOF
/* Generated by OmiSu — do not edit. Change with: omisu-theme <name> */
window {
  margin: 0;
  border: 2px solid #$ACCENT;
  border-radius: 12px;
  background-color: #$BG;
  color: #$FG;
}

#input {
  margin: 12px;
  border: 1px solid #$INACTIVE;
  border-radius: 8px;
  background-color: #$BG;
  color: #$FG;
  padding: 8px 12px;
  font-size: 14px;
}

#inner-box {
  margin: 0;
  padding: 8px;
}

#outer-box {
  margin: 0;
  padding: 0;
}

#scroll {
  margin: 0;
  padding: 0;
}

#entry:selected {
  background-color: #$ACCENT;
  color: #$BG;
  border-radius: 6px;
  margin: 2px 8px;
  padding: 8px 12px;
}

#entry {
  border-radius: 6px;
  margin: 2px 8px;
  padding: 8px 12px;
}

#entry:focus {
  background-color: alpha(#$ACCENT, 0.2);
}

#text {
  margin: 0;
  padding: 0;
}

#image {
  margin: 0 8px 0 0;
  padding: 0;
}
EOF

  # --- Wob theme -------------------------------------------------------------
  cat > "$share_dir/wob-theme.ini" <<EOF
# Generated by OmiSu — do not edit. Change with: omisu-theme <name>
[wob]
background-color = #${BG}cc
border-color = #00000000
border-size = 4
bar-color = #${ACCENT}c0
overflow-bar-color = #f38ba8
overflow-background-color = #${BG}cc
overflow-border-color = #00000000
anchor = bottom right
margin = 20
width = 300
height = 36
timeout = 1500
EOF

  # --- hyprlock theme (fallback when Quickshell lock is unavailable) ---------
  cat > "$share_dir/hyprlock.conf" <<EOF
# Generated by OmiSu — do not edit. Change with: omisu-theme <name>
background {
    monitor =
    color = rgb($BG)
}

input-field {
    monitor =
    size = 300, 48
    outline_thickness = 2
    outer_color = rgb($ACCENT)
    inner_color = rgb($INACTIVE)
    font_color = rgb($FG)
    placeholder_text = Password...
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = \$TIME
    color = rgb($FG)
    font_size = 48
    position = 0, 120
    halign = center
    valign = center
}
EOF

  # --- TriliumNext theme -----------------------------------------------------
  omisu_theme_triliumnext "$name" "$ACCENT" "$BG" "$FG" "$INACTIVE"

  # --- Shell env (read by the Quickshell shell via Quickshell.env) ------------
  cat > "$share_dir/theme.env" <<EOF
# Generated by OmiSu — do not edit. Change with: omisu-theme <name>
export OMISU_BG="#$BG"
export OMISU_FG="#$FG"
export OMISU_ACCENT="#$ACCENT"
export OMISU_INACTIVE="#$INACTIVE"
EOF

  # --- Wallpaper ------------------------------------------------------------
  # Point the Quickshell background layer (and lock screen) at this theme image.
  local wp_src="$root/wallpapers/$name.png"
  local wp_dir="$share_dir/wallpapers"
  local wp_dest="$wp_dir/$name.png"
  local state_dir="$omisu_home/.local/state/omisu"
  local background_link="$state_dir/current/background"
  mkdir -p "$wp_dir" "$state_dir/current"
  if [[ -f $wp_src ]]; then
    cp -f "$wp_src" "$wp_dest"
    cp -f "$wp_src" "$wp_dir/default.png"
    ln -nsf "$wp_dest" "$background_link"
    if command -v omisu-shell >/dev/null 2>&1; then
      omisu-shell -q background set "$wp_dest" 2>/dev/null || true
    elif command -v hyprctl >/dev/null 2>&1 && [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]; then
      hyprctl hyprpaper wallpaper ",$wp_dir/default.png" 2>/dev/null || true
    fi
  fi

  # --- Active theme marker ---------------------------------------------------
  echo "$name" > "$share_dir/active-theme"
  printf '%s\n' "$name" > "$state_dir/current/theme.name"
  chown -R "$omisu_user:" "$omisu_home/.config" "$omisu_home/.local" 2>/dev/null || true
  if command -v omisu-plymouth-set-by-theme >/dev/null; then
    sudo omisu-plymouth-set-by-theme "$name" 2>/dev/null || true
  fi
  echo "OmiSu: theme set to '$name'"
}

omisu_list_themes() {
  local root
  root="$(omisu_theme_root)"
  local t
  for t in "$root"/themes/flat/*; do
    [[ -f "$t" ]] && basename "$t"
  done
}